export interface DexEntry {
  id: number
  name: string
  types: string[]
}

export const SPRITE_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon'

export const spriteUrl = (id: number): string => `${SPRITE_BASE}/${id}.png`

export const TYPE_COLORS: Record<string, string> = {
  normal: '#a8a878', fire: '#f08030', water: '#6890f0', electric: '#f8d030',
  grass: '#78c850', ice: '#98d8d8', fighting: '#c03028', poison: '#a040a0',
  ground: '#e0c068', flying: '#a890f0', psychic: '#f85888', bug: '#a8b820',
  rock: '#b8a038', ghost: '#705898', dragon: '#7038f8', dark: '#705848',
  steel: '#b8b8d0', fairy: '#ee99ac',
}

export const TYPE_NAMES: Record<string, string> = {
  normal: 'Normal', fire: 'Fuego', water: 'Agua', electric: 'Eléctrico',
  grass: 'Planta', ice: 'Hielo', fighting: 'Lucha', poison: 'Veneno',
  ground: 'Tierra', flying: 'Volador', psychic: 'Psíquico', bug: 'Bicho',
  rock: 'Roca', ghost: 'Fantasma', dragon: 'Dragón', dark: 'Siniestro',
  steel: 'Acero', fairy: 'Hada',
}

export const ALL_TYPES = Object.keys(TYPE_NAMES)

export const POKEDEX: DexEntry[] = [
  { id: 1, name: 'Bulbasaur', types: ['grass', 'poison'] },
  { id: 2, name: 'Ivysaur', types: ['grass', 'poison'] },
  { id: 3, name: 'Venusaur', types: ['grass', 'poison'] },
  { id: 4, name: 'Charmander', types: ['fire'] },
  { id: 5, name: 'Charmeleon', types: ['fire'] },
  { id: 6, name: 'Charizard', types: ['fire', 'flying'] },
  { id: 7, name: 'Squirtle', types: ['water'] },
  { id: 8, name: 'Wartortle', types: ['water'] },
  { id: 9, name: 'Blastoise', types: ['water'] },
  { id: 10, name: 'Caterpie', types: ['bug'] },
  { id: 12, name: 'Butterfree', types: ['bug', 'flying'] },
  { id: 16, name: 'Pidgey', types: ['normal', 'flying'] },
  { id: 25, name: 'Pikachu', types: ['electric'] },
  { id: 26, name: 'Raichu', types: ['electric'] },
  { id: 35, name: 'Clefairy', types: ['fairy'] },
  { id: 37, name: 'Vulpix', types: ['fire'] },
  { id: 39, name: 'Jigglypuff', types: ['normal', 'fairy'] },
  { id: 41, name: 'Zubat', types: ['poison', 'flying'] },
  { id: 43, name: 'Oddish', types: ['grass', 'poison'] },
  { id: 52, name: 'Meowth', types: ['normal'] },
  { id: 54, name: 'Psyduck', types: ['water'] },
  { id: 58, name: 'Growlithe', types: ['fire'] },
  { id: 60, name: 'Poliwag', types: ['water'] },
  { id: 63, name: 'Abra', types: ['psychic'] },
  { id: 66, name: 'Machop', types: ['fighting'] },
  { id: 69, name: 'Bellsprout', types: ['grass', 'poison'] },
  { id: 72, name: 'Tentacool', types: ['water', 'poison'] },
  { id: 74, name: 'Geodude', types: ['rock', 'ground'] },
  { id: 77, name: 'Ponyta', types: ['fire'] },
  { id: 79, name: 'Slowpoke', types: ['water', 'psychic'] },
  { id: 81, name: 'Magnemite', types: ['electric', 'steel'] },
  { id: 84, name: 'Doduo', types: ['normal', 'flying'] },
  { id: 88, name: 'Grimer', types: ['poison'] },
  { id: 90, name: 'Shellder', types: ['water'] },
  { id: 92, name: 'Gastly', types: ['ghost', 'poison'] },
  { id: 95, name: 'Onix', types: ['rock', 'ground'] },
  { id: 96, name: 'Drowzee', types: ['psychic'] },
  { id: 98, name: 'Krabby', types: ['water'] },
  { id: 100, name: 'Voltorb', types: ['electric'] },
  { id: 102, name: 'Exeggcute', types: ['grass', 'psychic'] },
  { id: 104, name: 'Cubone', types: ['ground'] },
  { id: 106, name: 'Hitmonlee', types: ['fighting'] },
  { id: 108, name: 'Lickitung', types: ['normal'] },
  { id: 109, name: 'Koffing', types: ['poison'] },
  { id: 111, name: 'Rhyhorn', types: ['ground', 'rock'] },
  { id: 113, name: 'Chansey', types: ['normal'] },
  { id: 116, name: 'Horsea', types: ['water'] },
  { id: 118, name: 'Goldeen', types: ['water'] },
  { id: 120, name: 'Staryu', types: ['water'] },
  { id: 122, name: 'Mr. Mime', types: ['psychic', 'fairy'] },
  { id: 123, name: 'Scyther', types: ['bug', 'flying'] },
  { id: 125, name: 'Electabuzz', types: ['electric'] },
  { id: 126, name: 'Magmar', types: ['fire'] },
  { id: 127, name: 'Pinsir', types: ['bug'] },
  { id: 128, name: 'Tauros', types: ['normal'] },
  { id: 129, name: 'Magikarp', types: ['water'] },
  { id: 130, name: 'Gyarados', types: ['water', 'flying'] },
  { id: 131, name: 'Lapras', types: ['water', 'ice'] },
  { id: 133, name: 'Eevee', types: ['normal'] },
  { id: 134, name: 'Vaporeon', types: ['water'] },
  { id: 135, name: 'Jolteon', types: ['electric'] },
  { id: 136, name: 'Flareon', types: ['fire'] },
  { id: 143, name: 'Snorlax', types: ['normal'] },
  { id: 144, name: 'Articuno', types: ['ice', 'flying'] },
  { id: 145, name: 'Zapdos', types: ['electric', 'flying'] },
  { id: 146, name: 'Moltres', types: ['fire', 'flying'] },
  { id: 147, name: 'Dratini', types: ['dragon'] },
  { id: 149, name: 'Dragonite', types: ['dragon', 'flying'] },
  { id: 150, name: 'Mewtwo', types: ['psychic'] },
  { id: 151, name: 'Mew', types: ['psychic'] },
  { id: 196, name: 'Espeon', types: ['psychic'] },
  { id: 197, name: 'Umbreon', types: ['dark'] },
  { id: 212, name: 'Scizor', types: ['bug', 'steel'] },
  { id: 248, name: 'Tyranitar', types: ['rock', 'dark'] },
  { id: 254, name: 'Sceptile', types: ['grass'] },
  { id: 257, name: 'Blaziken', types: ['fire', 'fighting'] },
  { id: 260, name: 'Swampert', types: ['water', 'ground'] },
  { id: 282, name: 'Gardevoir', types: ['psychic', 'fairy'] },
  { id: 350, name: 'Milotic', types: ['water'] },
  { id: 373, name: 'Salamence', types: ['dragon', 'flying'] },
  { id: 376, name: 'Metagross', types: ['steel', 'psychic'] },
  { id: 445, name: 'Garchomp', types: ['dragon', 'ground'] },
  { id: 448, name: 'Lucario', types: ['fighting', 'steel'] },
  { id: 17, name: 'Pidgeotto', types: ['normal', 'flying'] },
  { id: 20, name: 'Raticate', types: ['normal'] },
  { id: 22, name: 'Fearow', types: ['normal', 'flying'] },
  { id: 24, name: 'Arbok', types: ['poison'] },
  { id: 28, name: 'Sandslash', types: ['ground'] },
  { id: 34, name: 'Nidoking', types: ['poison', 'ground'] },
  { id: 36, name: 'Clefable', types: ['fairy'] },
  { id: 38, name: 'Ninetales', types: ['fire'] },
  { id: 42, name: 'Golbat', types: ['poison', 'flying'] },
  { id: 45, name: 'Vileplume', types: ['grass', 'poison'] },
  { id: 51, name: 'Dugtrio', types: ['ground'] },
  { id: 53, name: 'Persian', types: ['normal'] },
  { id: 55, name: 'Golduck', types: ['water'] },
  { id: 57, name: 'Primeape', types: ['fighting'] },
  { id: 59, name: 'Arcanine', types: ['fire'] },
  { id: 65, name: 'Alakazam', types: ['psychic'] },
  { id: 68, name: 'Machamp', types: ['fighting'] },
  { id: 71, name: 'Victreebel', types: ['grass', 'poison'] },
  { id: 73, name: 'Tentacruel', types: ['water', 'poison'] },
  { id: 76, name: 'Golem', types: ['rock', 'ground'] },
  { id: 78, name: 'Rapidash', types: ['fire'] },
  { id: 80, name: 'Slowbro', types: ['water', 'psychic'] },
  { id: 82, name: 'Magneton', types: ['electric', 'steel'] },
  { id: 85, name: 'Dodrio', types: ['normal', 'flying'] },
  { id: 89, name: 'Muk', types: ['poison'] },
  { id: 94, name: 'Gengar', types: ['ghost', 'poison'] },
  { id: 99, name: 'Kingler', types: ['water'] },
  { id: 101, name: 'Electrode', types: ['electric'] },
  { id: 103, name: 'Exeggutor', types: ['grass', 'psychic'] },
  { id: 105, name: 'Marowak', types: ['ground'] },
  { id: 107, name: 'Hitmonchan', types: ['fighting'] },
  { id: 114, name: 'Tangela', types: ['grass'] },
  { id: 115, name: 'Kangaskhan', types: ['normal'] },
  { id: 117, name: 'Seadra', types: ['water'] },
  { id: 119, name: 'Seaking', types: ['water'] },
  { id: 121, name: 'Starmie', types: ['water', 'psychic'] },
  { id: 124, name: 'Jynx', types: ['ice', 'psychic'] },
  { id: 132, name: 'Ditto', types: ['normal'] },
  { id: 137, name: 'Porygon', types: ['normal'] },
  { id: 139, name: 'Omastar', types: ['rock', 'water'] },
  { id: 141, name: 'Kabutops', types: ['rock', 'water'] },
  { id: 142, name: 'Aerodactyl', types: ['rock', 'flying'] },
  { id: 148, name: 'Dragonair', types: ['dragon'] },
  { id: 152, name: 'Chikorita', types: ['grass'] },
  { id: 153, name: 'Bayleef', types: ['grass'] },
  { id: 154, name: 'Meganium', types: ['grass'] },
  { id: 155, name: 'Cyndaquil', types: ['fire'] },
  { id: 156, name: 'Quilava', types: ['fire'] },
  { id: 157, name: 'Typhlosion', types: ['fire'] },
  { id: 158, name: 'Totodile', types: ['water'] },
  { id: 159, name: 'Croconaw', types: ['water'] },
  { id: 160, name: 'Feraligatr', types: ['water'] },
  { id: 163, name: 'Hoothoot', types: ['normal', 'flying'] },
  { id: 169, name: 'Crobat', types: ['poison', 'flying'] },
  { id: 176, name: 'Togetic', types: ['fairy', 'flying'] },
  { id: 179, name: 'Mareep', types: ['electric'] },
  { id: 181, name: 'Ampharos', types: ['electric'] },
  { id: 182, name: 'Bellossom', types: ['grass'] },
  { id: 183, name: 'Marill', types: ['water', 'fairy'] },
  { id: 184, name: 'Azumarill', types: ['water', 'fairy'] },
  { id: 186, name: 'Politoed', types: ['water'] },
  { id: 189, name: 'Jumpluff', types: ['grass', 'flying'] },
  { id: 190, name: 'Aipom', types: ['normal'] },
  { id: 195, name: 'Quagsire', types: ['water', 'ground'] },
  { id: 199, name: 'Slowking', types: ['water', 'psychic'] },
  { id: 202, name: 'Wobbuffet', types: ['psychic'] },
  { id: 206, name: 'Dunsparce', types: ['normal'] },
  { id: 208, name: 'Steelix', types: ['steel', 'ground'] },
  { id: 210, name: 'Granbull', types: ['fairy'] },
  { id: 214, name: 'Heracross', types: ['bug', 'fighting'] },
  { id: 215, name: 'Sneasel', types: ['dark', 'ice'] },
  { id: 219, name: 'Magcargo', types: ['fire', 'rock'] },
  { id: 221, name: 'Piloswine', types: ['ice', 'ground'] },
  { id: 222, name: 'Corsola', types: ['water', 'rock'] },
  { id: 224, name: 'Octillery', types: ['water'] },
  { id: 225, name: 'Delibird', types: ['ice', 'flying'] },
  { id: 227, name: 'Skarmory', types: ['steel', 'flying'] },
  { id: 229, name: 'Houndoom', types: ['dark', 'fire'] },
  { id: 230, name: 'Kingdra', types: ['water', 'dragon'] },
  { id: 232, name: 'Donphan', types: ['ground'] },
  { id: 233, name: 'Porygon2', types: ['normal'] },
  { id: 238, name: 'Smoochum', types: ['ice', 'psychic'] },
  { id: 240, name: 'Magby', types: ['fire'] },
  { id: 242, name: 'Blissey', types: ['normal'] },
  { id: 243, name: 'Raikou', types: ['electric'] },
  { id: 244, name: 'Entei', types: ['fire'] },
  { id: 245, name: 'Suicune', types: ['water'] },
  { id: 249, name: 'Lugia', types: ['psychic', 'flying'] },
  { id: 250, name: 'Ho-Oh', types: ['fire', 'flying'] },
  { id: 251, name: 'Celebi', types: ['psychic', 'grass'] },
  { id: 252, name: 'Treecko', types: ['grass'] },
  { id: 253, name: 'Grovyle', types: ['grass'] },
  { id: 255, name: 'Torchic', types: ['fire'] },
  { id: 256, name: 'Combusken', types: ['fire', 'fighting'] },
  { id: 258, name: 'Mudkip', types: ['water'] },
  { id: 259, name: 'Marshtomp', types: ['water', 'ground'] },
  { id: 263, name: 'Zigzagoon', types: ['normal'] },
  { id: 272, name: 'Ludicolo', types: ['water', 'grass'] },
  { id: 275, name: 'Shiftry', types: ['grass', 'dark'] },
  { id: 279, name: 'Pelipper', types: ['water', 'flying'] },
  { id: 280, name: 'Ralts', types: ['psychic', 'fairy'] },
  { id: 284, name: 'Masquerain', types: ['bug', 'flying'] },
  { id: 286, name: 'Breloom', types: ['grass', 'fighting'] },
  { id: 291, name: 'Ninjask', types: ['bug', 'flying'] },
  { id: 292, name: 'Shedinja', types: ['bug', 'ghost'] },
  { id: 297, name: 'Hariyama', types: ['fighting'] },
  { id: 299, name: 'Nosepass', types: ['rock'] },
  { id: 302, name: 'Sableye', types: ['dark', 'ghost'] },
  { id: 303, name: 'Mawile', types: ['steel', 'fairy'] },
  { id: 306, name: 'Aggron', types: ['steel', 'rock'] },
  { id: 308, name: 'Medicham', types: ['fighting', 'psychic'] },
  { id: 310, name: 'Manectric', types: ['electric'] },
  { id: 315, name: 'Roselia', types: ['grass', 'poison'] },
  { id: 319, name: 'Sharpedo', types: ['water', 'dark'] },
  { id: 321, name: 'Wailord', types: ['water'] },
  { id: 323, name: 'Camerupt', types: ['fire', 'ground'] },
  { id: 324, name: 'Torkoal', types: ['fire'] },
  { id: 330, name: 'Flygon', types: ['ground', 'dragon'] },
  { id: 332, name: 'Cacturne', types: ['grass', 'dark'] },
  { id: 334, name: 'Altaria', types: ['dragon', 'flying'] },
  { id: 336, name: 'Seviper', types: ['poison'] },
  { id: 338, name: 'Solrock', types: ['rock', 'psychic'] },
  { id: 340, name: 'Whiscash', types: ['water', 'ground'] },
  { id: 342, name: 'Crawdaunt', types: ['water', 'dark'] },
  { id: 344, name: 'Claydol', types: ['ground', 'psychic'] },
  { id: 348, name: 'Armaldo', types: ['rock', 'bug'] },
  { id: 352, name: 'Kecleon', types: ['normal'] },
  { id: 354, name: 'Banette', types: ['ghost'] },
  { id: 357, name: 'Tropius', types: ['grass', 'flying'] },
  { id: 358, name: 'Chimecho', types: ['psychic'] },
  { id: 359, name: 'Absol', types: ['dark'] },
  { id: 362, name: 'Glalie', types: ['ice'] },
  { id: 365, name: 'Walrein', types: ['ice', 'water'] },
  { id: 367, name: 'Huntail', types: ['water'] },
  { id: 368, name: 'Gorebyss', types: ['water'] },
  { id: 371, name: 'Bagon', types: ['dragon'] },
  { id: 372, name: 'Shelgon', types: ['dragon'] },
  { id: 374, name: 'Beldum', types: ['steel', 'psychic'] },
  { id: 375, name: 'Metang', types: ['steel', 'psychic'] },
  { id: 377, name: 'Regirock', types: ['rock'] },
  { id: 378, name: 'Regice', types: ['ice'] },
  { id: 379, name: 'Registeel', types: ['steel'] },
  { id: 380, name: 'Latias', types: ['dragon', 'psychic'] },
  { id: 381, name: 'Latios', types: ['dragon', 'psychic'] },
  { id: 382, name: 'Kyogre', types: ['water'] },
  { id: 383, name: 'Groudon', types: ['ground'] },
  { id: 384, name: 'Rayquaza', types: ['dragon', 'flying'] },
  { id: 385, name: 'Jirachi', types: ['steel', 'psychic'] },
  { id: 387, name: 'Turtwig', types: ['grass'] },
  { id: 390, name: 'Chimchar', types: ['fire'] },
  { id: 393, name: 'Piplup', types: ['water'] },
  { id: 398, name: 'Staraptor', types: ['normal', 'flying'] },
  { id: 400, name: 'Bibarel', types: ['normal', 'water'] },
  { id: 405, name: 'Luxray', types: ['electric'] },
  { id: 406, name: 'Budew', types: ['grass', 'poison'] },
  { id: 407, name: 'Roserade', types: ['grass', 'poison'] },
  { id: 409, name: 'Rampardos', types: ['rock'] },
  { id: 411, name: 'Bastiodon', types: ['rock', 'steel'] },
  { id: 416, name: 'Vespiquen', types: ['bug', 'flying'] },
  { id: 419, name: 'Floatzel', types: ['water'] },
  { id: 424, name: 'Ambipom', types: ['normal'] },
  { id: 426, name: 'Drifblim', types: ['ghost', 'flying'] },
  { id: 428, name: 'Lopunny', types: ['normal'] },
  { id: 429, name: 'Mismagius', types: ['ghost'] },
  { id: 432, name: 'Purugly', types: ['normal'] },
  { id: 433, name: 'Chingling', types: ['psychic'] },
  { id: 437, name: 'Bronzong', types: ['steel', 'psychic'] },
  { id: 442, name: 'Spiritomb', types: ['ghost', 'dark'] },
  { id: 443, name: 'Gible', types: ['dragon', 'ground'] },
  { id: 444, name: 'Gabite', types: ['dragon', 'ground'] },
  { id: 450, name: 'Hippowdon', types: ['ground'] },
  { id: 452, name: 'Drapion', types: ['poison', 'dark'] },
  { id: 454, name: 'Toxicroak', types: ['poison', 'fighting'] },
  { id: 460, name: 'Abomasnow', types: ['grass', 'ice'] },
  { id: 461, name: 'Weavile', types: ['dark', 'ice'] },
  { id: 462, name: 'Magnezone', types: ['electric', 'steel'] },
  { id: 464, name: 'Rhyperior', types: ['ground', 'rock'] },
  { id: 466, name: 'Electivire', types: ['electric'] },
  { id: 467, name: 'Magmortar', types: ['fire'] },
  { id: 468, name: 'Togekiss', types: ['fairy', 'flying'] },
  { id: 470, name: 'Leafeon', types: ['grass'] },
  { id: 471, name: 'Glaceon', types: ['ice'] },
  { id: 472, name: 'Gliscor', types: ['ground', 'flying'] },
  { id: 473, name: 'Mamoswine', types: ['ice', 'ground'] },
  { id: 474, name: 'Porygon-Z', types: ['normal'] },
  { id: 475, name: 'Gallade', types: ['psychic', 'fighting'] },
  { id: 477, name: 'Dusknoir', types: ['ghost'] },
  { id: 478, name: 'Froslass', types: ['ice', 'ghost'] },
  { id: 479, name: 'Rotom', types: ['electric', 'ghost'] },
  { id: 482, name: 'Azelf', types: ['psychic'] },
  { id: 484, name: 'Palkia', types: ['water', 'dragon'] },
  { id: 485, name: 'Heatran', types: ['fire', 'steel'] },
  { id: 487, name: 'Giratina', types: ['ghost', 'dragon'] },
  { id: 488, name: 'Cresselia', types: ['psychic'] },
  { id: 491, name: 'Darkrai', types: ['dark'] },
  { id: 493, name: 'Arceus', types: ['normal'] },
  { id: 494, name: 'Victini', types: ['psychic', 'fire'] },
  { id: 497, name: 'Serperior', types: ['grass'] },
  { id: 500, name: 'Emboar', types: ['fire', 'fighting'] },
  { id: 503, name: 'Samurott', types: ['water'] },
  { id: 510, name: 'Liepard', types: ['dark'] },
  { id: 519, name: 'Pidove', types: ['normal', 'flying'] },
  { id: 526, name: 'Gigalith', types: ['rock'] },
  { id: 527, name: 'Woobat', types: ['psychic', 'flying'] },
  { id: 530, name: 'Excadrill', types: ['ground', 'steel'] },
  { id: 537, name: 'Seismitoad', types: ['water', 'ground'] },
  { id: 545, name: 'Scolipede', types: ['bug', 'poison'] },
  { id: 547, name: 'Whimsicott', types: ['grass', 'fairy'] },
  { id: 549, name: 'Lilligant', types: ['grass'] },
  { id: 553, name: 'Krookodile', types: ['ground', 'dark'] },
  { id: 555, name: 'Darmanitan', types: ['fire'] },
  { id: 560, name: 'Scrafty', types: ['dark', 'fighting'] },
  { id: 563, name: 'Cofagrigus', types: ['ghost'] },
  { id: 567, name: 'Archeops', types: ['rock', 'flying'] },
  { id: 569, name: 'Garbodor', types: ['poison'] },
  { id: 571, name: 'Zoroark', types: ['dark'] },
  { id: 573, name: 'Cinccino', types: ['normal'] },
  { id: 576, name: 'Gothitelle', types: ['psychic'] },
  { id: 579, name: 'Reuniclus', types: ['psychic'] },
  { id: 584, name: 'Vanilluxe', types: ['ice'] },
  { id: 586, name: 'Sawsbuck', types: ['normal', 'grass'] },
  { id: 587, name: 'Emolga', types: ['electric', 'flying'] },
  { id: 589, name: 'Escavalier', types: ['bug', 'steel'] },
  { id: 591, name: 'Amoonguss', types: ['grass', 'poison'] },
  { id: 593, name: 'Jellicent', types: ['water', 'ghost'] },
  { id: 596, name: 'Galvantula', types: ['electric', 'bug'] },
  { id: 598, name: 'Ferrothorn', types: ['grass', 'steel'] },
  { id: 601, name: 'Klinklang', types: ['steel'] },
  { id: 604, name: 'Eelektross', types: ['electric'] },
  { id: 609, name: 'Chandelure', types: ['ghost', 'fire'] },
  { id: 612, name: 'Haxorus', types: ['dragon'] },
  { id: 614, name: 'Beartic', types: ['ice'] },
  { id: 617, name: 'Accelgor', types: ['bug'] },
  { id: 621, name: 'Druddigon', types: ['dragon'] },
  { id: 623, name: 'Golurk', types: ['ground', 'ghost'] },
  { id: 625, name: 'Bisharp', types: ['dark', 'steel'] },
  { id: 628, name: 'Braviary', types: ['normal', 'flying'] },
  { id: 630, name: 'Mandibuzz', types: ['dark', 'flying'] },
  { id: 632, name: 'Durant', types: ['bug', 'steel'] },
  { id: 635, name: 'Hydreigon', types: ['dark', 'dragon'] },
  { id: 637, name: 'Volcarona', types: ['bug', 'fire'] },
  { id: 638, name: 'Cobalion', types: ['steel', 'fighting'] },
  { id: 639, name: 'Terrakion', types: ['rock', 'fighting'] },
  { id: 640, name: 'Virizion', types: ['grass', 'fighting'] },
  { id: 642, name: 'Thundurus', types: ['electric', 'flying'] },
  { id: 643, name: 'Reshiram', types: ['dragon', 'fire'] },
  { id: 644, name: 'Zekrom', types: ['dragon', 'electric'] },
  { id: 646, name: 'Kyurem', types: ['dragon', 'ice'] },
  { id: 647, name: 'Keldeo', types: ['water', 'fighting'] },
  { id: 649, name: 'Genesect', types: ['bug', 'steel'] },
  { id: 650, name: 'Chespin', types: ['grass'] },
  { id: 653, name: 'Fennekin', types: ['fire'] },
  { id: 656, name: 'Froakie', types: ['water'] },
  { id: 663, name: 'Talonflame', types: ['fire', 'flying'] },
  { id: 666, name: 'Vivillon', types: ['bug', 'flying'] },
  { id: 668, name: 'Pyroar', types: ['fire', 'normal'] },
  { id: 671, name: 'Florges', types: ['fairy'] },
  { id: 673, name: 'Gogoat', types: ['grass'] },
  { id: 675, name: 'Pangoro', types: ['fighting', 'dark'] },
  { id: 678, name: 'Meowstic', types: ['psychic'] },
  { id: 681, name: 'Aegislash', types: ['steel', 'ghost'] },
  { id: 685, name: 'Slurpuff', types: ['fairy'] },
  { id: 687, name: 'Malamar', types: ['dark', 'psychic'] },
  { id: 691, name: 'Dragalge', types: ['poison', 'dragon'] },
  { id: 695, name: 'Heliolisk', types: ['electric', 'normal'] },
  { id: 697, name: 'Tyrantrum', types: ['rock', 'dragon'] },
  { id: 698, name: 'Amaura', types: ['rock', 'ice'] },
  { id: 700, name: 'Sylveon', types: ['fairy'] },
  { id: 701, name: 'Hawlucha', types: ['fighting', 'flying'] },
  { id: 706, name: 'Goodra', types: ['dragon'] },
  { id: 707, name: 'Klefki', types: ['steel', 'fairy'] },
  { id: 709, name: 'Trevenant', types: ['ghost', 'grass'] },
  { id: 710, name: 'Pumpkaboo', types: ['ghost', 'grass'] },
  { id: 713, name: 'Avalugg', types: ['ice'] },
  { id: 714, name: 'Noivern', types: ['flying', 'dragon'] },
  { id: 715, name: 'Xerneas', types: ['fairy'] },
  { id: 716, name: 'Yveltal', types: ['dark', 'flying'] },
  { id: 717, name: 'Zygarde', types: ['dragon', 'ground'] },
  { id: 722, name: 'Rowlet', types: ['grass', 'flying'] },
  { id: 725, name: 'Litten', types: ['fire'] },
  { id: 728, name: 'Popplio', types: ['water'] },
  { id: 738, name: 'Vikavolt', types: ['bug', 'electric'] },
  { id: 743, name: 'Ribombee', types: ['bug', 'fairy'] },
  { id: 745, name: 'Lycanroc', types: ['rock'] },
  { id: 746, name: 'Wishiwashi', types: ['water'] },
  { id: 752, name: 'Araquanid', types: ['water', 'bug'] },
  { id: 758, name: 'Salazzle', types: ['poison', 'fire'] },
  { id: 759, name: 'Stufful', types: ['normal', 'fighting'] },
  { id: 762, name: 'Steenee', types: ['grass'] },
  { id: 766, name: 'Passimian', types: ['fighting'] },
  { id: 769, name: 'Sandygast', types: ['ghost', 'ground'] },
  { id: 773, name: 'Silvally', types: ['normal'] },
  { id: 774, name: 'Minior', types: ['rock', 'flying'] },
  { id: 778, name: 'Mimikyu', types: ['ghost', 'fairy'] },
  { id: 781, name: 'Dhelmise', types: ['ghost', 'grass'] },
  { id: 784, name: 'Kommo-o', types: ['dragon', 'fighting'] },
  { id: 787, name: 'Tapu Koko', types: ['electric', 'fairy'] },
  { id: 792, name: 'Lunala', types: ['psychic', 'ghost'] },
  { id: 793, name: 'Nihilego', types: ['rock', 'poison'] },
  { id: 799, name: 'Guzzlord', types: ['dark', 'dragon'] },
  { id: 800, name: 'Necrozma', types: ['psychic'] },
  { id: 801, name: 'Magearna', types: ['steel', 'fairy'] },
  { id: 802, name: 'Marshadow', types: ['fighting', 'ghost'] },
  { id: 810, name: 'Grookey', types: ['grass'] },
  { id: 813, name: 'Scorbunny', types: ['fire'] },
  { id: 816, name: 'Sobble', types: ['water'] },
  { id: 826, name: 'Orbeetle', types: ['bug', 'psychic'] },
  { id: 828, name: 'Thievul', types: ['dark'] },
  { id: 834, name: 'Drednaw', types: ['water', 'rock'] },
  { id: 837, name: 'Rolycoly', types: ['rock'] },
  { id: 841, name: 'Flapple', types: ['grass', 'dragon'] },
  { id: 842, name: 'Appletun', types: ['grass', 'dragon'] },
  { id: 845, name: 'Cramorant', types: ['flying', 'water'] },
  { id: 849, name: 'Toxtricity', types: ['electric', 'poison'] },
  { id: 851, name: 'Centiskorch', types: ['fire', 'bug'] },
  { id: 855, name: 'Polteageist', types: ['ghost'] },
  { id: 858, name: 'Hatterene', types: ['psychic', 'fairy'] },
  { id: 861, name: 'Grimmsnarl', types: ['dark', 'fairy'] },
  { id: 862, name: 'Obstagoon', types: ['dark', 'normal'] },
  { id: 863, name: 'Perrserker', types: ['steel'] },
  { id: 864, name: 'Cursola', types: ['ghost'] },
  { id: 865, name: 'Sirfetch\'d', types: ['fighting'] },
  { id: 866, name: 'Mr. Rime', types: ['ice', 'psychic'] },
  { id: 868, name: 'Milcery', types: ['fairy'] },
  { id: 871, name: 'Pincurchin', types: ['electric'] },
  { id: 872, name: 'Snom', types: ['ice', 'bug'] },
  { id: 874, name: 'Stonjourner', types: ['rock'] },
  { id: 875, name: 'Eiscue', types: ['ice'] },
  { id: 877, name: 'Morpeko', types: ['electric', 'dark'] },
  { id: 879, name: 'Copperajah', types: ['steel'] },
  { id: 881, name: 'Arctozolt', types: ['electric', 'ice'] },
  { id: 884, name: 'Duraludon', types: ['steel', 'dragon'] },
  { id: 888, name: 'Zacian', types: ['fairy'] },
  { id: 889, name: 'Zamazenta', types: ['fighting'] },
  { id: 890, name: 'Eternatus', types: ['poison', 'dragon'] },
  { id: 893, name: 'Zarude', types: ['dark', 'grass'] },
  { id: 906, name: 'Sprigatito', types: ['grass'] },
  { id: 909, name: 'Fuecoco', types: ['fire'] },
  { id: 912, name: 'Quaxly', types: ['water'] },
  { id: 918, name: 'Scovillain', types: ['grass', 'fire'] },
  { id: 923, name: 'Pawmot', types: ['electric', 'fighting'] },
  { id: 929, name: 'Dolliv', types: ['grass'] },
  { id: 933, name: 'Nacli', types: ['rock'] },
  { id: 936, name: 'Armarouge', types: ['fire', 'psychic'] },
  { id: 937, name: 'Ceruledge', types: ['fire', 'ghost'] },
  { id: 941, name: 'Kilowattrel', types: ['electric', 'flying'] },
  { id: 947, name: 'Bombirdier', types: ['dark', 'flying'] },
  { id: 950, name: 'Klawf', types: ['rock'] },
  { id: 954, name: 'Espathra', types: ['psychic'] },
  { id: 958, name: 'Tinkaton', types: ['fairy', 'steel'] },
  { id: 962, name: 'Dondozo', types: ['water'] },
  { id: 964, name: 'Veluza', types: ['water', 'psychic'] },
  { id: 967, name: 'Cyclizar', types: ['dragon', 'normal'] },
  { id: 970, name: 'Glimmora', types: ['rock', 'poison'] },
  { id: 972, name: 'Houndstone', types: ['ghost'] },
  { id: 978, name: 'Tatsugiri', types: ['dragon', 'water'] },
  { id: 979, name: 'Annihilape', types: ['fighting', 'ghost'] },
  { id: 980, name: 'Clodsire', types: ['poison', 'ground'] },
  { id: 981, name: 'Farigiraf', types: ['normal', 'psychic'] },
  { id: 982, name: 'Dudunsparce', types: ['normal'] },
  { id: 983, name: 'Kingambit', types: ['dark', 'steel'] },
  { id: 984, name: 'Great Tusk', types: ['ground', 'fighting'] },
  { id: 985, name: 'Iron Treads', types: ['ground', 'steel'] },
  { id: 994, name: 'Iron Moth', types: ['fire', 'poison'] },
  { id: 995, name: 'Iron Thorns', types: ['rock', 'electric'] },
  { id: 998, name: 'Baxcalibur', types: ['dragon', 'ice'] },
  { id: 999, name: 'Gimmighoul', types: ['ghost'] },
  { id: 1000, name: 'Gholdengo', types: ['steel', 'ghost'] },
  { id: 1001, name: 'Wo-Chien', types: ['dark', 'grass'] },
  { id: 1002, name: 'Chien-Pao', types: ['dark', 'ice'] },
  { id: 1003, name: 'Ting-Lu', types: ['dark', 'ground'] },
  { id: 1004, name: 'Chi-Yu', types: ['dark', 'fire'] },
  { id: 1007, name: 'Koraidon', types: ['fighting', 'dragon'] },
  { id: 1008, name: 'Miraidon', types: ['electric', 'dragon'] },
]

export const FISH_POOL: DexEntry[] = [
  { id: 129, name: 'Magikarp', types: ['water'] },
  { id: 118, name: 'Goldeen', types: ['water'] },
  { id: 119, name: 'Seaking', types: ['water'] },
  { id: 60, name: 'Poliwag', types: ['water'] },
  { id: 61, name: 'Poliwhirl', types: ['water'] },
  { id: 116, name: 'Horsea', types: ['water'] },
  { id: 90, name: 'Shellder', types: ['water'] },
  { id: 98, name: 'Krabby', types: ['water'] },
  { id: 120, name: 'Staryu', types: ['water'] },
  { id: 72, name: 'Tentacool', types: ['water', 'poison'] },
  { id: 170, name: 'Chinchou', types: ['water', 'electric'] },
  { id: 223, name: 'Remoraid', types: ['water'] },
  { id: 318, name: 'Carvanha', types: ['water', 'dark'] },
  { id: 320, name: 'Wailmer', types: ['water'] },
  { id: 339, name: 'Barboach', types: ['water', 'ground'] },
  { id: 349, name: 'Feebas', types: ['water'] },
  { id: 370, name: 'Luvdisc', types: ['water'] },
  { id: 456, name: 'Finneon', types: ['water'] },
  { id: 194, name: 'Wooper', types: ['water', 'ground'] },
]

export function randomFrom<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)]
}

export function shuffle<T>(items: T[]): T[] {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export function formatDexId(id: number): string {
  return `#${String(id).padStart(3, '0')}`
}
